name: Main

permissions:
  contents: read

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@d09ffc8ad6437bc278897279e33150d8e39ee3d5  # main as of 2026-10-03; includes Swift 6.4 inputs
    with:
      minimum_swift_version: "6.3"
      linux_6_2_enabled: false
      linux_6_3_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_6_4_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  static-sdk:
    name: Static Linux Swift SDK
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@d09ffc8ad6437bc278897279e33150d8e39ee3d5  # main as of 2026-10-03; includes Swift 6.4 inputs

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@d09ffc8ad6437bc278897279e33150d8e39ee3d5  # main as of 2026-10-03; includes Swift 6.4 inputs
    with:
      minimum_swift_version: "6.3"
      linux_6_2_enabled: false

  foundation-linking:
    name: Foundation linking
    uses: vapor/ci/.github/workflows/check-foundation-linking.yml@ad78413e13bebb9158083aa226608e028754106b  # main as of 2026-09-23
    with:
      swift_image: swift:6.3-noble
